### ISSUE TITLE
Not All XCCDF Rule-Result Values Are Parsed

### ISSUE THREAD

**Issue by Gerosolina** [Vulnerator/Vulnerator#66]
ACAS version 6.1.4 still does not show the items that the SCAP tool did not review. In order to get a vulnerator report with SCAP data that shows items that are not reviewed, I still have to run my data through STIG viewer and then save a .CKL file and then import that to vulnerator. It would be great if the vulnerator tool could take raw SCAP data and show the not reviewed items by the SCAP tool so that the people who analyze the systems could use the out put from vulnerator to finish there manual review. If you need further explanation on how I was able to get useable data out of vulnerator for a complete accurate report please contact me at David.Gerosolina@navy.mil

**Comment by amkuchta** [comment]
@Gerosolina Currently, Vulnerator only has a hard-coded value for the `pass` rule result - everything else defaults to a failed state.

For v6.2.0, I will include some logic on how to handle the rest of the enumerated rule-results, as denoted [here](https://scap.nist.gov/specifications/xccdf/xccdf_element_dictionary.html#resultEnumType).

I should have this one implemented in a few days (more about workload than actual level of effort) - if you'd like, I can send you a copy as a "test" release (since it should be tested before being launched, anyway, and I don't have any XCCDF files on hand that have non-reviewed findings).

**Comment by amkuchta** [comment]
Also, I didn't know whether or not to label this as a "Bug" or "Enhancement", so I chose both 😆

**Comment by Gerosolina** [comment]
I can test a copy for you if you would like.

David Gerosolina, CISSP
LSODS Information Systems Security Officer
NAVAIR
Office#: (732) 323-2880
David.Gerosolina@Navy.mil



-----Original Message-----
