### ISSUE TITLE
POAM Output

### ISSUE THREAD

**Issue by dubandrew** [Vulnerator/Vulnerator#78]
I'm sure there is something I'm doing wrong but when I execute a POAM from a .ckl the comments are being added to the Mitigation statement (Column G) vice the comments (Column O).  I tried this from both the older and newer version of DISA STIG viewer.  Am I supposed to use another program to generate the .ckl? I added a test sample to show what is happening

[New Viewer Test.xlsx](https://github.com/Vulnerator/Vulnerator/files/698094/New.Viewer.Test.xlsx)

**Comment by Moe0303** [comment]
I think it is supposed to be like that.  Unfortunately, the STIG viewer doesn't have a "mitigations" section.  So if you were going to detail mitigations within the STIG, it would likely be in the comments section.

**Comment by amkuchta** [comment]
@dubandrew I set the application to dump both the "Comments" and "Finding Details" sections into the "Mitigation" column on the POA&M by design.  The reason for this is that some users place their mitigation statement in "Comments", while others use "Finding Details" - to placing both options in Column G accommodates both sub-groups.

If you'd like comments in the "Comments" field, I suggest the following "work-around":

1.  "Vulnerate" your findings once with only the "Comments" option selected under the "STIG Mitigation Text Location" sub-heading; save the file
2.  Run the application again with only the "Finding Details" option selected; save the file under a different name than the first pass
3.  From the first file, copy and paste the Column G into Column O of the second document

This is a bit of a manual process, but it should satisfy your requirement with very minimal effort.

**Comment by dubandrew** [comment]
I have found STIGS to be an art and not a science so I understand the variations in how different organizations perform them.  Not that our way is better than anyone else but we leave the "comments" section for the Technician to add their comments, and the "Finding Details" to show the exact issue, or sometimes it gets populated with the long string of text from XCCDF file.  Once the POAM is generated the mitigation statements are added.  This creates a natural left to right flow in the POAM providing the Raw Severity Value (column F) prior to the mitigation statement, the Mitigation Statement (Column G) explaining the controls or procedures in place to mitigate it down, and then the new Severity Value (Column H).  Lastly, the technicians comments are in the "comments" section of the POAM so the reviewer can see everything without opening each .ckl.  

As I stated there is no science to this and I have been using the cut/paste workaround but thought I would at least ask.  Thanks for the feedback!
